# FoodSeg103 Dataset Exploration
---

This notebook aims to explore the **FoodSeg103** dataset, which contains images of various food items along with their segmentation masks. The goal is to analyze the dataset structure, visualize sample images, and prepare the data for further processing in computer vision tasks, such as image segmentation and classification.

### Import libraries
---

In [1]:
import numpy as np
import pandas as pd
import cv2
from datasets import load_dataset
import matplotlib.pyplot as plt

from src.utils.dataset import load_foodseg103, decode_image_from_bytes
from src.utils.visualization import show_image_preview

from src.constants.category_id import CATEGORY_ID

c:\Users\ferna\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

### Read dataset
---

In [2]:
train_df = load_foodseg103(type="train")

In [3]:
train_df.head()

,image,label,classes_on_image,id
0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"[0, 48, 66, 90]",0
1,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"[0, 52, 70, 82, 93]",1
2,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"[0, 58, 67]",2
3,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"[0, 48, 84, 85, 87]",3
4,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"[0, 46, 84, 87, 96, 101]",4

### Exploratory data analisys
---

In [5]:
train_df["image_decoded"] = train_df["image"].apply(decode_image_from_bytes)
train_df["annotation_mask"] = train_df["label"].apply(decode_image_from_bytes)

In [6]:
train_df.head()

,image,label,classes_on_image,id,image_decoded,annotation_mask
0,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"[0, 48, 66, 90]",0,"[[[34, 60, 61], [32, 56, 60], [32, 53, 58], [3...","[[90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90, ..."
1,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"[0, 52, 70, 82, 93]",1,"[[[39, 51, 65], [39, 51, 65], [39, 48, 65], [3...","[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
2,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"[0, 58, 67]",2,"[[[95, 99, 102], [107, 111, 114], [114, 119, 1...","[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
3,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"[0, 48, 84, 85, 87]",3,"[[[237, 231, 219], [238, 232, 220], [238, 232,...","[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."
4,{'bytes': b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x...,{'bytes': b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHD...,"[0, 46, 84, 87, 96, 101]",4,"[[[31, 50, 92], [27, 45, 83], [17, 36, 68], [1...","[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,..."

In [7]:
train_df.dtypes

image               object
label               object
classes_on_image    object
id                   int64
image_decoded       object
annotation_mask     object
dtype: object

In [ ]:
memory_usage = train_df.memory_usage(deep=True).sum()/(1024 ** 3)
print(f"Dataframe is consuming {round(memory_usage)} Mb")

### Visualization

In [ ]:
num_examples = 3
for image_id in range(num_examples):
    show_image_preview(train_df, image_id)

### References
---

[1] https://www.kaggle.com/code/siddhantrout/foodseg103-eda

[2] https://github.com/jamesjg/FoodSAM